apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy3
  labels:
    app: app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      name: deployment-pods
      labels:
        app: app-v1
    spec:
      volumes:
        - name: pv-storage  # You can give any name.
          persistentVolumeClaim:
            claimName: test-pvc
      containers:
        - name: ctr-1
          image: devopstrainer/deploy:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: pv-storage
