
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1 
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
