apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: test-pvc
    labels:
       type: local
spec:
   storageClassName: manual
   accessModes:
   - ReadWriteMany
   resources:
     requests:
       storage: 1
