apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      name: php-pods
      labels:
        app: php
    spec:
      imagePullSecrets:
        - name: ecr-key
      containers:
      - name: php
        image: 629008889621.dkr.ecr.ap-south-1.amazonaws.com/php:12
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: php-svc
  labels:
    app: php
spec:
  type: NodePort
  selector:
    app: php
  ports:
  - port: 80
    protocol: TCP
    nodePort: 32006



